name: Release

on:
  push:
    tags:
      - '*'

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
  CARGO_TERM_COLOR: always

permissions:
  contents: write

defaults:
  run:
    shell: bash

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - TARGET: x86_64-unknown-linux-musl
            OS: ubuntu-latest
            FEATURES: openssl-vendored
          - TARGET: aarch64-apple-darwin
            OS: macos-latest
            FEATURES: default-feature
          - TARGET: x86_64-pc-windows-msvc
            OS: windows-latest
            FEATURES: default-feature
    runs-on: ${{ matrix.OS }}
    env:
      NAME: sdl-cli
      TARGET: ${{ matrix.TARGET }}
      OS: ${{ matrix.OS }}
      FEATURES: ${{ matrix.FEATURES }}
    steps:
      - uses: actions/checkout@v4

      - name: Init submodules
        uses: snickerbockers/submodules-init@v4

      - name: Cargo cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ./target
          key: build-cargo-registry-${{ matrix.TARGET }}

      - name: Use strawberry perl
        if: startsWith(matrix.os, 'windows')
        run: echo OPENSSL_SRC_PERL=C:/Strawberry/perl/bin/perl >> $GITHUB_ENV

      - name: List workspace
        run: find ./

      - name: Install and configure dependencies
        run: |
          rustup set auto-self-update disable

          if [[ $OS =~ ^ubuntu.*$ ]]; then
            sudo apt-get update
            sudo apt-get install clang llvm musl-tools libboost-all-dev libc6-dev -y
          fi

          rustup toolchain install stable
          rustup default stable

          rustup -V

          cat >>~/.cargo/config <<EOF
          [target.x86_64-unknown-linux-musl]
          rustflags = ["-C", "target-feature=+crt-static","-C", "strip=symbols"]
          [target.x86_64-pc-windows-msvc]
          rustflags = ["-C", "target-feature=+crt-static","-C", "strip=symbols"]
          [target.aarch64-apple-darwin]
          rustflags = ["-C", "target-feature=+crt-static","-C", "strip=symbols"]
          EOF

      - name: Install rust target
        run: rustup target add $TARGET

      - name: Build sdl-cli
        run: cargo build --package sdl-cli --release --verbose --target $TARGET --features $FEATURES

      - name: List target
        run: find ./target

      - name: Compress
        run: |
          mkdir -p ./artifacts
          if [[ $OS =~ ^windows.*$ ]]; then
              EXEC_SDL=sdl.exe
              EXEC_SDL_SERVICE=sdl-service.exe
          else
              EXEC_SDL=sdl
              EXEC_SDL_SERVICE=sdl-service
          fi
          if [[ $GITHUB_REF_TYPE =~ ^tag$ ]]; then
            TAG=$GITHUB_REF_NAME
          else
            TAG=$GITHUB_SHA
          fi
          if [[ $OS =~ ^windows.*$ ]]; then
            ARCHIVE_NAME=sdl-$TARGET-$TAG.zip
          else
            ARCHIVE_NAME=sdl-$TARGET-$TAG.tar.gz
          fi
          mv ./target/$TARGET/release/$EXEC_SDL ./artifacts/$EXEC_SDL
          mv ./target/$TARGET/release/$EXEC_SDL_SERVICE ./artifacts/$EXEC_SDL_SERVICE
          mv ./README ./artifacts/README.txt
          cd ./artifacts
          if [[ $OS =~ ^windows.*$ ]]; then
            powershell.exe -NoLogo -NoProfile -Command "Compress-Archive -Path * -DestinationPath '$ARCHIVE_NAME'"
          else
            tar -czf "$ARCHIVE_NAME" *
          fi
          mkdir upload_file
          mv "$ARCHIVE_NAME" ./upload_file/

      - name: Archive artifact
        uses: actions/upload-artifact@v4
        with:
          name: sdl-cli-${{ matrix.TARGET }}
          path: ./artifacts/upload_file

  deploy:
    if: startsWith(github.ref, 'refs/tags/')
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      - name: List artifacts
        run: find ./artifacts

      - name: Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./artifacts/**/*.tar.gz
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
